kind: Job 
apiVersion: batch/v1 
metadata:
  name: jobexample 
spec:
  template:
    spec:
      containers: 
      - name: jobcontainer 
        image: docker/whalesay 
        command: ["cowsay","This is job Example"]
      restartPolicy: Never 
  backoffLimit: 4
  activeDeadlineSeconds: 200
